// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Grid.Forecast.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Grid.Forecast
{
    /// <summary>
    /// Builds and executes requests for operations under \grid\forecast
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ForecastRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiSdk.grid.forecast.item collection</summary>
        /// <param name="position">ID of dataset</param>
        /// <returns>A <see cref="global::ApiSdk.Grid.Forecast.Item.WithResource_ItemRequestBuilder"/></returns>
        public global::ApiSdk.Grid.Forecast.Item.WithResource_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("resource_id", position);
                return new global::ApiSdk.Grid.Forecast.Item.WithResource_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Grid.Forecast.ForecastRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForecastRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/grid/forecast", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Grid.Forecast.ForecastRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForecastRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/grid/forecast", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
