// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Station.Current;
using ApiSdk.Station.Historical;
using ApiSdk.Station.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Station
{
    /// <summary>
    /// Builds and executes requests for operations under \station
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The current property</summary>
        public global::ApiSdk.Station.Current.CurrentRequestBuilder Current
        {
            get => new global::ApiSdk.Station.Current.CurrentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The historical property</summary>
        public global::ApiSdk.Station.Historical.HistoricalRequestBuilder Historical
        {
            get => new global::ApiSdk.Station.Historical.HistoricalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ApiSdk.station.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ApiSdk.Station.Item.WithModeItemRequestBuilder"/></returns>
        public global::ApiSdk.Station.Item.WithModeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("mode", position);
                return new global::ApiSdk.Station.Item.WithModeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Station.StationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/station", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Station.StationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/station", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
