// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Timeseries.Historical.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOutput_formatQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "geojson")]
        #pragma warning disable CS1591
        Geojson,
        #pragma warning restore CS1591
        [EnumMember(Value = "csv")]
        #pragma warning disable CS1591
        Csv,
        #pragma warning restore CS1591
    }
}
