// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>An enumeration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Bundesland
    {
        [EnumMember(Value = "Burgenland")]
        #pragma warning disable CS1591
        Burgenland,
        #pragma warning restore CS1591
        [EnumMember(Value = "Kärnten")]
        #pragma warning disable CS1591
        Kärnten,
        #pragma warning restore CS1591
        [EnumMember(Value = "Niederösterreich")]
        #pragma warning disable CS1591
        Niederösterreich,
        #pragma warning restore CS1591
        [EnumMember(Value = "Oberösterreich")]
        #pragma warning disable CS1591
        Oberösterreich,
        #pragma warning restore CS1591
        [EnumMember(Value = "Salzburg")]
        #pragma warning disable CS1591
        Salzburg,
        #pragma warning restore CS1591
        [EnumMember(Value = "Steiermark")]
        #pragma warning disable CS1591
        Steiermark,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tirol")]
        #pragma warning disable CS1591
        Tirol,
        #pragma warning restore CS1591
        [EnumMember(Value = "Vorarlberg")]
        #pragma warning disable CS1591
        Vorarlberg,
        #pragma warning restore CS1591
        [EnumMember(Value = "Wien")]
        #pragma warning disable CS1591
        Wien,
        #pragma warning restore CS1591
    }
}
