// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>An enumeration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EndpointType
    {
        [EnumMember(Value = "grid")]
        #pragma warning disable CS1591
        Grid,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeseries")]
        #pragma warning disable CS1591
        Timeseries,
        #pragma warning restore CS1591
        [EnumMember(Value = "station")]
        #pragma warning disable CS1591
        Station,
        #pragma warning restore CS1591
    }
}
