// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>An enumeration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EndpointMode
    {
        [EnumMember(Value = "historical")]
        #pragma warning disable CS1591
        Historical,
        #pragma warning restore CS1591
        [EnumMember(Value = "current")]
        #pragma warning disable CS1591
        Current,
        #pragma warning restore CS1591
        [EnumMember(Value = "forecast")]
        #pragma warning disable CS1591
        Forecast,
        #pragma warning restore CS1591
    }
}
