// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>An enumeration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IdType
    {
        [EnumMember(Value = "Synop")]
        #pragma warning disable CS1591
        Synop,
        #pragma warning restore CS1591
        [EnumMember(Value = "Klima")]
        #pragma warning disable CS1591
        Klima,
        #pragma warning restore CS1591
    }
}
