// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>An enumeration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StationMetadataType
    {
        [EnumMember(Value = "COMBINED")]
        #pragma warning disable CS1591
        COMBINED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUB_STATION")]
        #pragma warning disable CS1591
        SUB_STATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "INDIVIDUAL")]
        #pragma warning disable CS1591
        INDIVIDUAL,
        #pragma warning restore CS1591
    }
}
