// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StationFilterResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The matching_stations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.StationMetadataDto>? MatchingStations { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.StationMetadataDto> MatchingStations { get; set; }
#endif
        /// <summary>The num_stations_matching property</summary>
        public int? NumStationsMatching { get; set; }
        /// <summary>The num_stations_total property</summary>
        public int? NumStationsTotal { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.StationFilterResponseDto"/> and sets the default values.
        /// </summary>
        public StationFilterResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.StationFilterResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.StationFilterResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.StationFilterResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "matching_stations", n => { MatchingStations = n.GetCollectionOfObjectValues<global::ApiSdk.Models.StationMetadataDto>(global::ApiSdk.Models.StationMetadataDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "num_stations_matching", n => { NumStationsMatching = n.GetIntValue(); } },
                { "num_stations_total", n => { NumStationsTotal = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.StationMetadataDto>("matching_stations", MatchingStations);
            writer.WriteIntValue("num_stations_matching", NumStationsMatching);
            writer.WriteIntValue("num_stations_total", NumStationsTotal);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
