// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Station.Item.Item.Filter;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Station.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \station\{mode}\{resource_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResource_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filter property</summary>
        public global::ApiSdk.Station.Item.Item.Filter.FilterRequestBuilder Filter
        {
            get => new global::ApiSdk.Station.Item.Item.Filter.FilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Station.Item.Item.WithResource_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResource_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/station/{mode}/{resource_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Station.Item.Item.WithResource_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResource_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/station/{mode}/{resource_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
