// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Timeseries.Forecast;
using ApiSdk.Timeseries.Historical;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Timeseries
{
    /// <summary>
    /// Builds and executes requests for operations under \timeseries
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimeseriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The forecast property</summary>
        public global::ApiSdk.Timeseries.Forecast.ForecastRequestBuilder Forecast
        {
            get => new global::ApiSdk.Timeseries.Forecast.ForecastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The historical property</summary>
        public global::ApiSdk.Timeseries.Historical.HistoricalRequestBuilder Historical
        {
            get => new global::ApiSdk.Timeseries.Historical.HistoricalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Timeseries.TimeseriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeseriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/timeseries", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Timeseries.TimeseriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeseriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/timeseries", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
